### ISSUE TITLE
cd doesn't show any error messages

### ISSUE THREAD

**Issue by username1366** [itmanagerro/puppet-bash_history#1]
When I run cd <non-existent-directory> I don't see any errors.

**Comment by itmanagerro** [comment]
Hi @username1366, can you please be more specific? An example perhaps?
Thank you

**Comment by itmanagerro** [comment]
Fixed with version 1.0.5

You can `puppet module upgrade itmanagerro-bash_history` safely.

Thank you!

> [root@localhost ~]# cd /nodir
> -bash: pushd: /nodir: No such file or directory
> [root@localhost ~]#
