### ISSUE TITLE
help module history

### ISSUE THREAD

**Issue by rafaelsilvaa10** [itmanagerro/puppet-bash_history#2]
Good Day . THIS WHAT Missing ?

[root@lnxxxxxxxxx04 ~]# puppet agent -t
Info: Using configured environment 'homolog'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Lookup of key 'bash_history::hh_clientip' failed: DataBinding 'hiera': undefined method `empty?' for nil:NilClass at /etc/puppetlabs/code/environments/homolog/manifests/site.pp:4:2 on node lnxxxxxxxxx04.dxxa.net
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by itmanagerro** [comment]
Hi Rafael,

You need to configure the class.

In Puppet manifest:

```
class { 'bash_history':
  hh_clientip => true,
  hh_terminal => true,
  hh_username => true,
}
```

Or hiera-like:

```
    hh_clientip: 'true'
    hh_terminal: 'true'
    hh_username: 'true'
```

**Comment by rafaelsilvaa10** [comment]
thanks for the feedback .

I add this in init.pp  ../modules/bash_history/manifests/init.pp ? 

below is my file init.pp 

```
# Class bash_history
class bash_history
(
  $hh_clientip = $::bash_history::params::ssh_clientip,
  $hh_terminal = $::bash_history::params::ssh_terminal,
  $hh_username = $::bash_history::params::ssh_username,
)
{
  include bash_history::config
  include bash_history::service
}
  hh_clientip => true ,
  hh_terminal => true ,
  hh_username => true ,
}

```

bellow file /etc/puppetlabs/code/environments/homolog/manifests/site.pp 

```
node "lnxpodppc04.dasa.net"{
        include homolog_aol_teste
        include homolog_aol
        include bash_history
        }
```

I not using Hiera.

from already thank you for the support

**Comment by itmanagerro** [comment]
Hi Rafael,

You don't need to modify the module, if you already altered the module, please reinstall it.
Then edit your site.pp with the following:

```
node "lnxpodppc04.dasa.net" {
  include homolog_aol_teste
  include homolog_aol
  # Include bash_history and configure the variables
  class { 'bash_history':
    hh_clientip => true,
    hh_terminal => true,
    hh_username => true,
  }
}
```

Remember that you'll need to edit sshd_config file with **PermitUserEnvironment yes** (sshd restart required), then add your SSH Keys into authorized_keys as:

`environment="REALUSER=Rafael" ssh-rsa AAAAB2NzA3za[...long string...]AD2jeOsYQ== Rafael SSH KEY
`

**Comment by rafaelsilvaa10** [comment]
Hello, we're almost there.

```
my site.pp : 
node "lnxpodppc04.dasa.net"{
        include homolog_aol_teste
        include homolog_aol
class {'bash_history':
        hh_clientip => true,
        hh_terminal => true,
        hh_username => true,
}
}

```

```

```

[root@lnxpodppc04 ~]# puppet agent -t
Info: Using configured environment 'homolog'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Caching catalog for lnxpodppc04.dasa.net
Info: Applying configuration version '1468237367'
Notice: /Stage[main]/Bash_history::Config/File[/etc/pbh/cd_func.sh]/ensure: defined content as '{md5}cc259a8cf2efdfb4a56d3a31fc779a95'
Notice: /Stage[main]/Bash_history::Config/File[/etc/pbh/loghistory_func.sh]/ensure: defined content as '{md5}64b7bd8a17ee4e3980c360ef70cfa204'
Notice: /Stage[main]/Bash_history::Config/File[/etc/pbh/puppet.bash_history]/ensure: defined content as '{md5}0bb1f56467ddb7b2aae4d8ffad6196a9'
Notice: Applied catalog in 0.15 seconds

``````

On client

```[root@lnxpodppc04 ~]# grep PermitUser /etc/ssh/sshd_config
PermitUserEnvironment yes

[root@lnxpodppc04 ~]# /etc/init.d/sshd restart


SSH with keys. 
``````

[rpereira@puppetserver ~]$ whoami
rpereira
[rpereira@puppetserver ~]$ ssh lnxpodppc04
Last login: Mon Jul 11 08:41:44 2016 from nbsp173612.dasa.net
[rpereira@lnxpodppc04 ~]$

```


I did not understand that part of sshkey
environment="REALUSER=Rafael" ssh-rsa AAAAB2NzA3zaGFD4tdg4tSss[...long string...]AD4fSArShnio3xB3cb2jeOsYQ== Rafael SSH KEY

```

**Comment by itmanagerro** [comment]
Yes, now the module is installed and SSH configured, now you'll need the SSH Key set in your username's ~/.ssh/authorized_keys

You'll need to have an SSH key-pair (public and private):
`ssh-keygen -t rsa -b 4096 -C "your_email@example.com"`

Manually: Get the content of id_rsa.pub and update the ~/.ssh/authorized_keys, then add at the beginning of the line the environment parameter
`environment="REALUSER=Rafael"`

Automated: Adding SSH Key to root user with Puppet (to work with bash_history environment)

```
# Add SSH Key for Mihai Cornateanu with nickname Mihai in /root/.ssh/authorized_keys
ssh_authorized_key { 'Mihai Cornateanu @ ITManager':
  ensure  => present,
  user    => 'root',
  type    => 'ssh-rsa',
  options => 'environment="REALUSER=Mihai"',
  key     => 'LONG STRING HERE',
}
```

"LONG STRING HERE" is found in id_rsa.pub
`cat id_rsa.pub | awk -F' ' '{print $2}'`

**Comment by itmanagerro** [comment]
As a hint... don't go for Puppet Explorer ... Foreman is much much much better!
https://www.theforeman.org

**Comment by rafaelsilvaa10** [comment]
Thank you, now work.

Great module , very useful .

**Comment by rafaelsilvaa10** [comment]
But the foreman , works nice in puppet 4x ? I'm using Puppet4

**Comment by itmanagerro** [comment]
Thank you Rafael
Whenever I'll find useful features for bash_history I'll add them to this module, please feel free to ask for help or features.

Foreman 1.12.0 is now available for new installations and upgrades, featuring **Puppet 4** support, Ubuntu 16.04 support and hundreds of improvements. Read about the changes in the release notes, and follow the quick start to install it.

I will close this issue now, best regards!
